############################################################
# 08) Volcano: balance vs evidence (→ progression)  (Fig6C)
# ----------------------------------------------------------
# Purpose:
#   Reproduce the already-generated volcano plot (Figure 6C)
#   without modifying any existing scripts (01–07).
#
# Inputs (generated by earlier scripts):
#   output/signed_effects_summary_withCI_{STAMP}.csv
#     (fallback: signed_effects_summary_{STAMP}.csv)
#
# Outputs:
#   fig_pub/volcano_balance_evidence_{STAMP}.pdf
#   fig_pub/volcano_balance_evidence_{STAMP}.png
#
# Notes:
# - Keeps *_var terms as-is (does NOT collapse to parent),
#   to match the provided Figure 6C.
# - Fixes the target outcome to progression (incl. FVC/DLCO decline).
############################################################

options(repos = c(CRAN = "https://cloud.r-project.org"), pkgType = "binary")

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(ggplot2)
  library(ggrepel)
  library(here)
  library(showtext)
})

############################################################
# 0) PATHS & FONT
############################################################
ROOT    <- here::here()
DIR_OUT <- file.path(ROOT, "output")
DIR_FIG <- file.path(ROOT, "fig_pub")
dir.create(DIR_FIG, recursive = TRUE, showWarnings = FALSE)

# Font (keep consistent with the other scripts)
cands <- c("Hiragino Sans","Hiragino Kaku Gothic ProN","Yu Gothic",
           "YuGothic","Noto Sans CJK JP","IPAexGothic","IPAGothic")
jpfont <- cands[cands %in% sysfonts::font_families()][1]
if (!length(jpfont) || is.na(jpfont)) jpfont <- "sans"
showtext_auto(enable = TRUE)

############################################################
# 1) Helpers (minimal; standalone)
############################################################
STOP_IF_EMPTY <- function(df, msg){
  if (is.null(df) || !nrow(df)) stop(msg, call. = FALSE)
  df
}

latest <- function(pattern, dirs){
  dirs <- unique(dirs)
  files <- unlist(lapply(dirs, function(d){
    if (!dir.exists(d)) return(character(0))
    list.files(d, pattern = pattern, full.names = TRUE)
  }))
  if (!length(files)) return(NA_character_)
  files[ which.max(file.info(files)$mtime) ]
}

safe_read <- function(path){
  if (is.na(path) || !nzchar(path) || !file.exists(path)) return(tibble())
  readr::read_csv(path, show_col_types = FALSE, guess_max = 100000)
}

# Canonicalization (match the conventions used elsewhere)
canon_A <- function(a){
  map <- c("SP-D"="SP_D","SP-A"="SP_A","KL-6"="KL6","MUC-5B"="MUC5B")
  a0 <- trimws(as.character(a))
  a0 <- ifelse(a0 %in% names(map), map[a0], a0)
  a0
}
canon_C <- function(c){
  c0 <- trimws(as.character(c))
  c0 <- gsub("AE[_ ]?ILD|AEILD|Acute exacerbation of ILD","AE-ILD",c0,ignore.case=TRUE)
  c0 <- gsub("death|all-cause mortality","mortality",c0,ignore.case=TRUE)
  c0 <- gsub("FVC ?(decline|drop|decrease)|decline in FVC","FVC_decline",c0,ignore.case=TRUE)
  c0 <- gsub("DLCO ?(decline|drop|decrease)|decline in DLCO","DLCO_decline",c0,ignore.case=TRUE)
  c0 <- gsub("hospitalisation","hospitalization",c0,ignore.case=TRUE)
  c0 <- gsub("progress|disease progression","progression",c0,ignore.case=TRUE)
  c0
}

############################################################
# 2) Load SIGNED summary (same source as 05/07)
############################################################
f_sum_ci <- latest("^signed_effects_summary_withCI_\\d{8}_\\d{4}\\.csv$", c(DIR_OUT))
f_sum    <- latest("^signed_effects_summary_\\d{8}_\\d{4}\\.csv$",       c(DIR_OUT))

SIGNED <- safe_read(f_sum_ci)
if (!nrow(SIGNED)) SIGNED <- safe_read(f_sum)
STOP_IF_EMPTY(SIGNED, "SIGNED summary not found in output/. Run 05 (or the step that creates signed_effects_summary_withCI_*.csv).")

# Derive STAMP from filename if possible
STAMP <- NA_character_
if (!is.na(f_sum_ci) && file.exists(f_sum_ci)) {
  STAMP <- sub("^.*signed_effects_summary_withCI_(\\d{8}_\\d{4})\\.csv$", "\\1", basename(f_sum_ci))
} else if (!is.na(f_sum) && file.exists(f_sum)) {
  STAMP <- sub("^.*signed_effects_summary_(\\d{8}_\\d{4})\\.csv$", "\\1", basename(f_sum))
}
if (is.na(STAMP) || !nzchar(STAMP)) STAMP <- format(Sys.time(), "%Y%m%d_%H%M")

############################################################
# 3) Build volcano table (→ progression)
############################################################
# IMPORTANT: keep *_var as-is to match the provided Figure 6C
SIGNED2 <- SIGNED %>%
  mutate(
    A = canon_A(A),
    C = canon_C(C)
  )

focus_set   <- c("progression","FVC_decline","DLCO_decline")  # progression family
focus_title <- "progression"

V <- SIGNED2 %>%
  filter(C %in% focus_set) %>%
  group_by(A) %>%
  summarise(
    pos = sum(pos_articles, na.rm = TRUE),
    neg = sum(neg_articles, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    balance  = (pos - neg) / pmax(1, pos + neg),
    evidence = log10(pmax(1, pos + neg)),
    score    = (abs(balance) + 0.20) * (evidence + 0.50)
  ) %>%
  arrange(desc(score))

STOP_IF_EMPTY(V, "No progression-related rows found (C in progression/FVC_decline/DLCO_decline).")

# Label top candidates (tune if you want more/less labels)
labN <- 24
V_lab <- V %>% slice_head(n = min(labN, nrow(V)))

############################################################
# 4) Plot (match the provided Figure 6C style)
############################################################
p_vol <- ggplot(V, aes(x = balance, y = evidence)) +
  geom_point(size = 2, alpha = 0.95) +
  ggrepel::geom_text_repel(
    data = V_lab,
    aes(label = A),
    size = 3,
    min.segment.length = 0,
    box.padding = 0.3,
    point.padding = 0.2,
    max.overlaps = Inf
  ) +
  coord_cartesian(xlim = c(-0.25, 1.02)) +
  labs(
    title = paste0("Volcano: balance vs evidence (\u2192 ", focus_title, ")"),
    x = "balance = (risk\u2191 \u2212 risk\u2193)/(risk\u2191 + risk\u2193)",
    y = "log10(# {risk\u2191 + risk\u2193})"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    text = element_text(family = jpfont),
    plot.title = element_text(size = 16),
    panel.grid.minor = element_blank()
  )

# Save
out_pdf <- file.path(DIR_FIG, paste0("volcano_balance_evidence_", STAMP, ".pdf"))
out_png <- file.path(DIR_FIG, paste0("volcano_balance_evidence_", STAMP, ".png"))
ggsave(out_pdf, p_vol, width = 12, height = 8, device = cairo_pdf)
ggsave(out_png, p_vol, width = 12, height = 8, dpi = 300)

message("Saved: ", out_pdf)
message("Saved: ", out_png)
message("=== DONE (08) ===")
